// OPERATIONS

export const GET_OPERATIONS = "GET_OPERATIONS";
export const GET_OPERATION = "GET_OPERATION";
export const CREATE_OPERATION = "CREATE_OPERATION";
export const UPDATE_OPERATION = "UPDATE_OPERATION";
export const DELETE_OPERATION = "DELETE_OPERATION";
export const CREATE_DETAIL_OPERATION = "CREATE_DETAIL_OPERATION";
export const CREATE_DETAIL_OPERATION_ANEST = "CREATE_DETAIL_OPERATION_ANEST";
export const CREATE_DETAIL_OPERATION_COOR = "CREATE_DETAIL_OPERATION_COOR";
export const GET_OPERATIONS_BY_USER = "GET_OPERATIONS_BY_USER";
export const GET_OPERATION_ARCHIVE = "GET_OPERATION_ARCHIVE";

// PATIENTS

export const GET_PATIENTS = "GET_PATIENTS";
export const GET_PATIENT = "GET_PATIENT";
export const CREATE_PATIENT = "CREATE_PATIENT";
export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const SEARCH_PATIENTS = "SEARCH_PATIENTS";

//PRODUCTS
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";

//EMPLOYEES

export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_EMPLOYEES_ALL = "GET_EMPLOYEES_ALL";
export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const SEARCH_EMPLOYEES = "SEARCH_EMPLOYEES";


//

export const GET_CHIRUGIENS = "GET_CHIRUGIENS";
export const GET_CHIRUGIEN = "GET_CHIRUGIEN";
export const CREATE_CHIRUGIEN = "CREATE_CHIRUGIEN";
export const UPDATE_CHIRUGIEN = "UPDATE_CHIRUGIEN";
export const DELETE_CHIRUGIEN = "DELETE_CHIRUGIEN";
export const SEARCH_CHIRUGIEN = "SEARCH_CHIRUGIEN";

// AUTH

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

//anesthesistes 


export const GET_ANESTHESISTES = "GET_ANESTHESISTES";

//COORDINATEUR

export const GET_COORDINATEURS = "GET_COORDINATEURS";

//SALLE

export const GET_SALLES = "GET_SALLES";
//STAT

export const GET_STAT = "GET_STAT";